#pragma once

enum EventOpcode {
    EVENT_EMPTY = 0,
    EVENT_CONNECT = 1,
    EVENT_DISCONNECT = 2,
    EVENT_ASSIGN = 3,
    EVENT_BIND = 4,
    EVENT_SCORE = 5,
    EVENT_PLAYER_INPUT = 6,
    EVENT_SPAWN = 7,
    EVENT_DESTROY = 8,
    EVENT_PICKUP_SPAWN = 9,
    EVENT_POSITION = 10,
    EVENT_ROTATION = 11,
    EVENT_EXPLOSION = 12,
    EVENT_HEALTH = 13,
    EVENT_AMMO_COUNT = 14,
    EVENT_EQUIP = 15,
    EVENT_PLAYER_STATUS = 16,
    EVENT_TIME = 17,
    EVENT_RELOAD_REQUEST = 100,
};
